apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: configmap-demo-pod
      image: alpine
      env:
        - name: KEY1
          valueFrom:
            configMapKeyRef:
              name: keyvalcfgmap
              key: key1
        - name: KEY2
          valueFrom:
            configMapKeyRef:
              name: keyvalcfgmap
              key: key2
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: keyvalcfgmap