apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-web-app
  labels:
    app: webapp-color
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-color
  template:
    metadata:
      labels:
        app: webapp-color
    spec:
      containers:
      - name: kodekloud
        image: kodekloud/webapp-color
        ports:
        - containerPort: 80