apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  type: ClusterIP
  ports:
    - port: 9376
      name: customport
      name: https
  selector:
    myapp: messaging
