apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-shaibitton
spec:
  containers:
  - image: redis:alpine
    name: redis-storage-shaibitton
    volumeMounts:
    - mountPath: /data/redis
      name: pv-analytics
  volumes:
  - name: pv-analytics
    emptyDir: {}
